callstackincubator/react-native-bottom-tabs

README.md

I hit this error when `pod install`
```bash
[!] CocoaPods could not find compatible versions for pod "react-native-bottom-tabs":
In Podfile:
react-native-bottom-tabs (from `../node_modules/react-native-bottom-tabs`)
Specs satisfying the `react-native-bottom-tabs (from `../node_modules/react-native-bottom-tabs`)` dependency were found, but they required a higher minimum deployment target.
```
So I update README about minimum iOS version.

Update README about minimum iOS version

---

src/TabView.tsx

This PR fixes issue https://github.com/okwasniewski/react-native-bottom-tabs/issues/13
Right now it will show a warning if there are more than 6 tabs on android and will only show 6 tabs and trims the other tabs.
https://github.com/user-attachments/assets/4ebfbffa-2c26-4332-b3b8-35d6337206db

fix: trim routes for android - no more then 6 tabs

---

README.md
example/src/Screens/Albums.tsx
example/src/Screens/Article.tsx
example/src/Screens/Chat.tsx
example/src/Screens/Contacts.tsx

This PR fixes content insets in examples.

fix: Add ScrollView adjustment automatic

---

package.json

Yo! Awesome work with this library, was testing it out with onestack.dev and this makes things a bit easier to set up with Vite.

fix: add react-navigation export to package.json

---

docs/docs/_meta.json

fixed a link in the header based on config in Re.Pack [here](https://github.com/callstack/repack/blob/main/website/src/4.x/_meta.json)

fix: docs link target in header

---

docs/docs/docs/guides/usage-with-react-navigation.md
example/src/App.tsx
example/src/Examples/FourTabs.tsx
ios/RCTTabViewViewManager.mm
ios/TabViewImpl.swift
ios/TabViewProvider.swift
src/TabView.tsx
src/TabViewNativeComponent.ts

This let's you define the edge appearance of the tabbar.
Allowing for a tabbar that is transparent when there is no content behind the tabbar.
@okwasniewski I am a bit in doubt what we should initially set this to... It seems that if you have a tabbarcontroller it modifies this to transparent by default? Do we want it transparent by default (on the scroll edge) or not... hmm...
_If the value of this property is nil, UIKit uses the value of the tab bar’s [standardAppearance](https://developer.apple.com/documentation/uikit/uitabbar/3198046-standardappearance) property, modified to have a transparent background. If no tab bar controller manages your tab bar, UIKit ignores this property and uses the tab bar’s standard appearance._

feat(iOS): scroll edge appearance

---

docs/docs/docs/getting-started/quick-start.mdx
docs/docs/docs/guides/_meta.json
docs/docs/docs/guides/android-native-styling.md
docs/docs/docs/guides/usage-with-one.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
docs/docs/styles/index.css
docs/rspress.config.ts

This PR adds: 
- Usage with onestack.dev
- Styling improvements
- Android Native Styling guide

docs: add new pages

---

android/src/main/java/com/rcttabview/RCTTabView.kt
android/src/main/java/com/rcttabview/RCTTabViewViewManager.kt
docs/docs/docs/guides/usage-with-react-navigation.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
example/src/App.tsx
example/src/Examples/FourTabs.tsx
src/TabView.tsx
src/TabViewNativeComponent.ts

Part of this: https://github.com/okwasniewski/react-native-bottom-tabs/issues/11
**Summary**: This PR updates the ripple color of tab bar click for Android implementations.
**Testing**:
Verified Ripple color changes on Android.
Added FourTabsRippleColor for visual changes.
Adding Video for reference
https://github.com/user-attachments/assets/7cb8e2eb-b56c-4546-824a-315b11bd80ca

Added support for rippleColor in android

---

docs/docs/docs/getting-started/_meta.json
docs/docs/docs/getting-started/how-is-it-different.mdx
docs/docs/docs/getting-started/introduction.mdx

This PR adds documentation around the differences between JS and Native bottom tabs

docs: document how Native Tabs differ from JS Tabs

---

android/src/main/java/com/rcttabview/RCTTabView.kt
android/src/main/java/com/rcttabview/RCTTabViewViewManager.kt
docs/docs/docs/guides/usage-with-react-navigation.md
example/src/App.tsx
example/src/Examples/FourTabs.tsx
ios/RCTTabViewViewManager.mm
ios/TabViewImpl.swift
ios/TabViewProvider.swift
src/TabView.tsx
src/TabViewNativeComponent.ts

Part of this: https://github.com/okwasniewski/react-native-bottom-tabs/issues/11
**Summary:** This PR updates the tab bar background color for both iOS and Android implementations.
**Changes Made:**
**iOS**: Added the updateTabBarAppearance(with:) function to set the background color using UITabBarAppearance for iOS 15 and barTintColor for earlier versions
**Android**: Updated the tab bar background color to apply uniformly.
**Testing:**
- Verified background color changes on both iOS and Android.
- Added `FourTabsWithBarTintColor` for visual changes.
Adding snapshot of changes here:
iOS:
Android:

Added support for barTintColor in android ios

---

android/src/main/java/com/rcttabview/RCTTabView.kt
android/src/main/java/com/rcttabview/RCTTabViewViewManager.kt
docs/docs/docs/guides/usage-with-react-navigation.mdx
example/src/App.tsx
example/src/Examples/NativeBottomTabs.tsx
example/src/Examples/TintColors.tsx
ios/Extensions.swift
ios/RCTTabViewViewManager.mm
ios/TabViewImpl.swift
ios/TabViewProvider.swift
package.json
src/TabView.tsx
src/TabViewAdapter.android.tsx
src/TabViewAdapter.tsx
src/TabViewNativeComponent.ts
src/react-navigation/navigators/createNativeBottomTabNavigator.tsx
src/react-navigation/types.ts
src/react-navigation/views/NativeBottomTabView.tsx
src/types.ts
yarn.lock

This pull request introduces a new feature that adds support for active/inactive tint colors on tabs across both Android and iOS components.
- **Color Handling:**  
The colors are sourced from the `react-navigation` theme by default. This follows the same approach used by `@react-navigation/bottom-tabs`. As a result, I added dependencies for `color` and `@types/color` to handle this functionality.
- **Android Implementation:**  
My Kotlin code might feel more Java-like, as I'm more familiar with Java. So, you’ll notice some usage of `as` and `if (x != null)` for type narrowing.
- **iOS Implementation:**  
As you may know, SwiftUI Tabs rely on the appearance of the UIKit tab bar. However, SwiftUI doesn't provide a built-in way to customize the inactive (unselected) tint color. To work …

Adding Active Inactive Tint Color

---

.github/workflows/ci.yml
android/src/main/java/com/rcttabview/RCTTabViewViewManager.kt
example/ios/Podfile.lock
example/src/Examples/NativeBottomTabs.tsx
ios/Extensions.swift
ios/Fabric/RCTTabViewComponentView.h
ios/Fabric/RCTTabViewComponentView.mm
ios/PageSelectedEvent.swift
ios/RCTTabViewViewManager.mm
ios/TabLongPressedEvent.swift
ios/TabViewImpl.swift
ios/TabViewProvider.swift
package.json
react-native-bottom-tabs.podspec
src/TabView.tsx
src/TabViewNativeComponent.ts

This PR implements new architecture for iOS.

feat(iOS): new arch

---

babel.config.js
package.json
yarn.lock

Fixes #87 
This fixes a warning that we got when running the library on Android:
`(NOBRIDGE) WARN  Codegen didn't run for RNCTabView. This will be an error in the future. Make sure you are using @react-native/babel-preset when building your JavaScript code.`
Looks like React Native now requires the user to transpile their code using the react native babel preset. This PR adds the babel preset to babel config and tells builder bob to use the preset.
This is a temporary fix and we will add this plugin directly to bob in the future.
1. Use yalc or package the library using `yarn pack`
2. Create a new React Native app and consume the package
3. Make sure there is no `NOBRIDGE) WARN  Codegen didn't run for RNCTabView. This will be an error in the future. Make sure you are using …

fix: codegen didn't run warning on android

---

android/src/main/java/com/rcttabview/RCTTabView.kt

This PR fixes a crash/warning on native side when there are no images passed to tab bar

fix: remove native warning when there are no images passed

---

app.plugin.js
docs/docs/docs/getting-started/quick-start.mdx
docs/docs/docs/guides/android-native-styling.md
package.json
src/expo.ts
yarn.lock

This PR should close: 
- #48 
- #40 
Api of the config plugin: 
```
"plugins": [
"react-native-bottom-tabs"
// or 
["react-native-bottom-tabs", { theme: "material2" }]
],
```

feat: introduce expo config plugin

---

docs/docs/docs/guides/_meta.json
docs/docs/docs/guides/usage-with-vector-icons.md
example/app.json
example/package.json
example/src/App.tsx
example/src/Examples/NativeBottomTabsVectorIcons.tsx
yarn.lock

This PR documents and adds new example with react-native-vector-icons
Closes: #15

feat: document usage with vector icons

---

docs/docs/docs/guides/usage-with-react-navigation.mdx

Resolves this: https://github.com/okwasniewski/react-native-bottom-tabs/issues/69 
- `backbehaviour` props added in docs.

feat(docs): back behaviour props added for Android

---

android/src/main/java/com/rcttabview/RCTTabView.kt
android/src/main/java/com/rcttabview/RCTTabViewImpl.kt
android/src/newarch/RCTTabViewManager.kt
android/src/oldarch/RCTTabViewManager.kt
docs/docs/docs/getting-started/how-is-it-different.mdx
docs/docs/docs/guides/usage-with-react-navigation.mdx
example/src/Examples/NativeBottomTabs.tsx
ios/Fabric/RCTTabViewComponentView.mm
ios/RCTTabViewViewManager.mm
ios/TabViewImpl.swift
ios/TabViewProvider.swift
src/TabView.tsx
src/TabViewNativeComponent.ts

This PR adds native support for haptic feedback!
It uses performHapticFeedback on Android and `UINotificationFeedbackGenerator` on iOS
It's enabled by default and can be disabled by passing `hapticFeedbackEnabled={false}` to the navigator

feat: native support for haptic feedback

---

docs/docs/docs/guides/usage-with-react-navigation.mdx

[usage-with-react-navigation](https://okwasniewski.github.io/react-native-bottom-tabs/docs/guides/usage-with-react-navigation.html) unable to view.
Reported the following error:
`react-native-bottom-tabs/docs/docs/docs/guides/usage-with-react-navigation.mdx`
> Error: "191:24: Unexpected end of file in expression, expected a corresponding closing brace for `{`"

docs: fix rspress compiler error

---

docs/docs/docs/getting-started/quick-start.mdx
docs/docs/docs/guides/usage-with-react-navigation.mdx
docs/docs/docs/guides/usage-with-vector-icons.md

This PR updates getting started guides

docs: update getting started

---

android/src/main/java/com/rcttabview/RCTTabView.kt
android/src/main/java/com/rcttabview/RCTTabViewImpl.kt
docs/docs/docs/guides/standalone-usage.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
example/src/App.tsx
example/src/Examples/FourTabs.tsx
example/src/Examples/NativeBottomTabsVectorIcons.tsx
ios/Fabric/RCTTabViewComponentView.mm
ios/TabViewImpl.swift
ios/TabViewProvider.swift
src/TabView.tsx
src/TabViewNativeComponent.ts
src/react-navigation/types.ts
src/react-navigation/views/NativeBottomTabView.tsx
src/types.ts

This PR should close #41 
It adds new option for routes namely `hidden: boolean`. 
Users can pass `hidden: true` (we can also make tabBarButton: () => null; work if necessary) and the tab is hidden until user navigates to it programatically, when he leaves the tab it disappears.
https://github.com/user-attachments/assets/13aa9037-894f-498a-b010-ebc86f0a3372
It's 1:1 match with JS bottom tabs behaviour 
https://github.com/user-attachments/assets/7ccd7298-c1b0-46ac-bb30-359e3bb2b2f7

feat: support hiding tabs

---

docs/docs/docs/guides/usage-with-react-navigation.mdx
example/src/Examples/NativeBottomTabsEmbeddedStacks.tsx
ios/TabViewImpl.swift
ios/TabViewProvider.swift
src/TabView.tsx
src/TabViewNativeComponent.ts

This PR changes `ignoresTopSafeArea` prop to true by default in order to match behavior from JS tabs. 
In 95% of cases users needed to add ignoresTopSafeArea anyways.

fix: change ignoresTopSafeArea defalt to true in order to match JS Tabs

---

src/TabView.tsx

This PR fixes an issue where if you have transparent background of the route it can be visible while being on a different route. 
This was also an issue on AndroidTV, cc: @douglowder

fix: hide routes with opacity 0 for Android

---

ios/Extensions.swift
ios/TabItemEventModifier.swift
ios/TabViewImpl.swift

This PR should fix: #124 
It's also a partial fix for #128, it appears that everything works properly with `scrollEdgeApperance="transparent"`. 
If we override `tabBar.scrollEdgeAppearance` then it's breaking. It is a bug in SwiftUI's tab view component which we can do nothing about 😢 (other than open a issue for apple)

fix: appearance handling on iOS

---

ios/PageSelectedEvent.swift
ios/TabLongPressedEvent.swift
ios/TabViewImpl.swift

The changes in #116 introduced noticeable rerendering in tvOS when using the arrow key or swipe gesture on the remote to change tabs.
The issue is that on tvOS, tabs are not selected by a press event, so the `onTabItemEvent()` handler is unnecessarily redrawing the tab bar.
This PR fixes that issue, and adds tvOS version checks to the existing iOS version checks.
Also fixed warnings in `PageSelectedEvent.swift`.

fix(iOS): various fixes for Apple TV

---

android/src/main/java/com/rcttabview/RCTTabView.kt
android/src/newarch/RCTTabViewManager.kt
android/src/oldarch/RCTTabViewManager.kt
docs/docs/docs/guides/standalone-usage.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
example/src/Examples/NativeBottomTabs.tsx
ios/Fabric/RCTTabViewComponentView.mm
ios/RCTTabViewViewManager.mm
ios/TabViewImpl.swift
ios/TabViewProvider.swift
src/TabView.tsx
src/TabViewNativeComponent.ts
src/types.ts

This PR adds custom font support.
Solves #107 
Fonts can be defined on the navigator level like so:
```tsx
<Tab.Navigator
tabLabelStyle={{
fontFamily: 'Avenir',
fontSize: 15,
}}
>
```

feat: add custom fonts support

---

docs/docs/docs/guides/edge-to-edge-support.md

This PR instructs users to use only use config plugin when using `react-native-edge-to-edge`.

docs: instruct users to use one config plugin

---

android/src/main/java/com/rcttabview/RCTTabView.kt
example/ios/Podfile.lock
ios/TabViewImpl.swift
ios/TabViewProvider.swift
react-native-bottom-tabs.podspec

This PR bumps SDWebImage to make it compatible with expo-image on iOS.

fix: bump SDWebImage

---

ios/TabViewImpl.swift

- Change to have tab bar correctly appear on first render (otherwise has the default gray color, and won't have correct appearance until tab selection changes)
- Fix compile error (`UIFont.smallSystemFontSize unavailable on tvOS`)

fix: tvOS compile error and appearance

---

ios/Extensions.swift

Version >=0.5.0 was failing to build on XCode 15.2:
```
func introspectTabView(closure: @escaping (UITabBarController) -> Void) -> some View {
44 |     self
> 45 |       .introspect(
|        ^ call to main actor-isolated instance method 'introspect' in a synchronous nonisolated context
```
I think it's related to a recent change to @MainActor in XCode 16?
Whatever the case, the package is building for me with this change 🙌

Fix ios build on old xcode

---

apps/example/ios/Podfile.lock
lefthook.yml
package.json
packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.mm
packages/react-native-bottom-tabs/ios/RCTTabViewViewManager.mm
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
yarn.lock

This PR removes unused `RCTImageLoader`, as it got replaced by `SDWebImage`.
CI Green

fix: remove unused image loader

---

.changeset/bright-pianos-invite.md
packages/react-navigation/src/types.ts
packages/react-navigation/src/views/NativeBottomTabView.tsx

This PR removes the tab bar icon workaround as it's not needed anymore 
CI Green
N/A

fix: remove tab bar icon workaround

---

.changeset/perfect-onions-reply.md
apps/example/ios/Podfile.lock
apps/example/src/Components/MusicControl.tsx
apps/example/src/Screens/Contacts.tsx
docs/docs/docs/guides/usage-with-react-navigation.mdx
packages/react-native-bottom-tabs/ios/Events/PageSelectedEvent.swift
packages/react-native-bottom-tabs/ios/Events/TabBarMeasuredEvent.swift
packages/react-native-bottom-tabs/ios/Events/TabLongPressedEvent.swift
packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.mm
packages/react-native-bottom-tabs/ios/RCTTabViewViewManager.mm
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
packages/react-native-bottom-tabs/src/TabView.tsx
packages/react-native-bottom-tabs/src/TabViewNativeComponent.ts
packages/react-native-bottom-tabs/src/index.tsx
packages/react-native-bottom-tabs/src/utils/BottomTabBarHeightContext.ts
packages/react-native-bottom-tabs/src/utils/useBottomTabBarHeight.ts

This PR implements `useBottomTabBarHeight` hook.
Closes: #96 
Check if height is properly returned. 
https://github.com/user-attachments/assets/3f943a69-f619-4dd0-9623-21e640d9cff8

feat: implement useBottomTabBarHeight

---

.changeset/modern-seas-pull.md
packages/react-native-bottom-tabs/ios/TabViewImpl.swift

This PR correctly handles scrollEdgeApperance transparent active indicator text, reported in #164 
Follow steps in #164
https://github.com/user-attachments/assets/a7227010-6b75-405e-9a47-16da5b1c52b6

fix(ios): correctly handle active items for scroll edge transparent

---

packages/react-native-bottom-tabs/README.md
packages/react-navigation/README.md

feat: add README to packages

---

.changeset/orange-pandas-exercise.md
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/ImageSource.kt
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt

This PR starts of the work done by @Peek-A-Booo, should handle more image sources. 
Check if all image sources are working now.
Tested in release mode:

fix(android): Handle tabBarIcon sources

---

packages/react-native-bottom-tabs/ios/TabViewImpl.swift

In scrollEdgeAppearance : 'transparent' mode the active tab appear its label with inactive tint color

Fix a bug that active tab label shows with inactive color

---

.changeset/hungry-readers-remember.md
apps/example/ios/Podfile.lock
apps/example/src/Examples/NativeBottomTabsEmbeddedStacks.tsx
packages/react-native-bottom-tabs/ios/Events/OnNativeLayoutEvent.swift
packages/react-native-bottom-tabs/ios/Events/PageSelectedEvent.swift
packages/react-native-bottom-tabs/ios/Events/TabBarMeasuredEvent.swift
packages/react-native-bottom-tabs/ios/Events/TabLongPressedEvent.swift
packages/react-native-bottom-tabs/ios/Extensions.swift
packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.mm
packages/react-native-bottom-tabs/ios/RCTTabViewViewManager.mm
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
packages/react-native-bottom-tabs/src/TabView.tsx
packages/react-native-bottom-tabs/src/TabViewNativeComponent.ts

This PR introduces measuring available space for views so that they get laid out properly. This is internal only change that doesnt affect public API.
This should also unblock #46 
Should fix: 
- #165
- #161 
Check above issues after applying those changes.
N/A

fix: measure available space for views on iOS

---

docs/docs/docs/guides/standalone-usage.md
docs/docs/docs/guides/usage-with-react-navigation.mdx

Default value is wrong because labels are by default hidden on Android when tab is not focused.

fix(docs): wrong default value for labeled prop

---

.changeset/popular-oranges-provide.md
.github/workflows/ci.yml
apps/example/macos/Podfile
apps/example/macos/Podfile.lock
apps/example/metro.config.js
apps/example/package.json
apps/example/src/App.tsx
apps/example/src/Examples/NativeBottomTabsSVGs.tsx
apps/example/src/Examples/SFSymbols.tsx
package.json
packages/react-native-bottom-tabs/ios/Extensions.swift
packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.h
packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.mm
packages/react-native-bottom-tabs/ios/PlatformAliases.swift
packages/react-native-bottom-tabs/ios/RCTTabViewViewManager.mm
packages/react-native-bottom-tabs/ios/RepresentableView.swift
packages/react-native-bottom-tabs/ios/TabItem.swift
packages/react-native-bottom-tabs/ios/TabItemEventModifier.swift
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProps.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
packages/react-native-bottom-tabs/react-native-bottom-tabs.podspec
turbo.json
yarn.lock

This PR solves #46 
The view is not sized properly when using sidebar, it's width is always width of the window.

feat: macos support

---

.changeset/ninety-planets-sleep.md
packages/react-native-bottom-tabs/babel.config.js
packages/react-native-bottom-tabs/package.json
yarn.lock

Replaced RN babel preset in the main package with codegen plugin in order to prevent injecting `@babel/runtime` into the code when building the release version. 
This was causing issues in setup where `swc` is used instead of `babel` since `swc` has it's own helpers (equivalent of `@babel/runtime`). I believe helpers should be injected when bundling the project and not at the time of building the library, so there is no hard requirement of having `@babel/runtime` as a dependency in the project.
n/a

fix: replace RN babel preset with codegen plugin directly

---

.changeset/green-ravens-fail.md
apps/example/src/Examples/NativeBottomTabs.tsx
apps/example/src/Examples/ThreeTabs.tsx
docs/docs/docs/guides/standalone-usage.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabViewImpl.kt
packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.mm
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
packages/react-native-bottom-tabs/src/TabView.tsx
packages/react-native-bottom-tabs/src/TabViewNativeComponent.ts
packages/react-native-bottom-tabs/src/types.ts
packages/react-navigation/src/types.ts
packages/react-navigation/src/views/NativeBottomTabView.tsx

This PR adds support for `testID` which normal RN `View` has. So now it's possible to use E2E frameworks like Detox to click on tab item by `testID`.

feat: add support for testID

---

.github/workflows/ci.yml
apps/example/ios/Podfile
apps/example/macos/Podfile

This PR removes modular headers workaround and introduces newly created plugin to automatically fix this. 
CI Green

fix: remove modular headers workaround

---

.changeset/new-kiwis-clean.md
apps/example/ios/Podfile.lock
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/src/TabViewNativeComponent.ts
turbo.json

This PR properly sets translucent prop on iOS, thanks @jbroma for reporting the issue! 
Set `translucent={false}`

fix: properly set translucent prop on iOS

---

.changeset/smooth-terms-compete.md
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt
packages/react-native-bottom-tabs/android/src/oldarch/RCTTabViewManager.kt

This PR refactors Android event dispatching.

chore: refactor android event dispatching

---

.changeset/purple-baboons-rhyme.md
apps/example/ios/Podfile.lock
apps/example/src/App.tsx
apps/example/src/Examples/NativeBottomTabsFreezeOnBlur.tsx
packages/react-native-bottom-tabs/package.json
packages/react-native-bottom-tabs/src/Screen.tsx
packages/react-native-bottom-tabs/src/TabView.tsx
packages/react-native-bottom-tabs/src/types.ts
packages/react-navigation/src/types.ts
packages/react-navigation/src/views/NativeBottomTabView.tsx
yarn.lock

This PR continues the work of @shubhamguptadream11 🙏
Implementing freezeOnBlur
1. Go to freezeOnblur example
2. Check if navigating off the tab stops console.logs 
N/a

feat: implement `freezeOnBlur`

---

.changeset/mighty-carrots-worry.md
packages/react-native-bottom-tabs/android/build.gradle

This PR fixes blinking when selecting items on Android when all labels are shown. 
https://github.com/user-attachments/assets/6f2b9819-0e59-410d-83d0-4a80be298fbf
https://github.com/user-attachments/assets/bb2ebaa3-de94-45f8-be65-4dd2cf0a91cb

fix: blinking on Android

---

CONTRIBUTING.md

Update the documentation per latest structure.

readme: update contributing guidelines

---

packages/react-native-bottom-tabs/package.json
packages/react-navigation/package.json

Removes hardcoded `tsc` path from `package.json`, as without it it is still being resolved correctly and packages build as expected
Green CI, `yarn build` works correctly

chore: remove tsc path from package.json

---

.changeset/rare-berries-rush.md
apps/example/src/App.tsx
apps/example/src/Examples/FourTabs.tsx
apps/example/src/Examples/NativeBottomTabs.tsx
docs/docs/docs/guides/standalone-usage.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
packages/react-native-bottom-tabs/src/TabView.tsx

Fixes https://github.com/callstackincubator/react-native-bottom-tabs/issues/205. Moves `barTintColor` under `tabBarStyle`
Run `packages/example` app.

feat(breaking): create `tabBarStyle`

---

.changeset/cyan-horses-tie.md
CONTRIBUTING.md
docs/docs/docs/getting-started/quick-start.mdx
docs/docs/docs/guides/android-native-styling.mdx
docs/docs/docs/guides/edge-to-edge-support.md
docs/docs/docs/guides/usage-with-expo-router.mdx
docs/docs/docs/guides/usage-with-react-navigation.mdx
packages/react-native-bottom-tabs/src/expo.ts

This PR adds various documentation nad CONTRIBUTING fixes. 
It also introduces new Material You theme for Expo Config Plugin.

feat: introduce material you theme for Expo Config Plugin

---

.changeset/two-lobsters-exercise.md
apps/example/src/Examples/NativeBottomTabs.tsx
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt

This fixes the issue where android will crash when changing the tab bar label during run time crashes the app.
Fixes https://github.com/callstackincubator/react-native-bottom-tabs/issues/248
I have added a state change in the longPress event within the NativeBottomTabs example, this should change the first tab from "Article" to  "CHANGED".

fix: fix crash when change tab bar label during runtime

---

packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.mm
packages/react-native-bottom-tabs/ios/TabViewProvider.swift

Fixes crash when adding fontWeight as a label style on iOS, when built using old architecture
Create build with new arch disabled, and add fontWeight as a label style.

fix: fix crash on iOS when adding fontWeight on old arch builds

---

.changeset/orange-deers-stare.md
packages/react-native-bottom-tabs/ios/Extensions.swift

This PR should fix issues with keyboard shifting layout: #266, https://github.com/callstackincubator/react-native-bottom-tabs/discussions/255
Open keyboard
https://github.com/user-attachments/assets/f75c85b1-d490-44ec-a18a-8ebae7261d60

fix(iOS): properly handle measurements by ignoring keyboard

---

.changeset/fresh-pugs-suffer.md
docs/docs/docs/guides/usage-with-expo-router.mdx
packages/expo-template/app/(tabs)/_layout.tsx

This PR fixes `@bottom-tabs/expo-template` and updates documentation with information to supply proper typing for `withLayoutContext` in order to avoid `any` types.

docs: provide proper typings for withLayoutContext

---

.changeset/pretty-lemons-reply.md
apps/example/app.json
apps/example/ios/Podfile.lock
apps/example/package.json
apps/example/src/App.tsx
apps/example/src/Examples/NativeBottomTabsCustomTabBar.tsx
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabViewImpl.kt
packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt
packages/react-native-bottom-tabs/android/src/oldarch/RCTTabViewManager.kt
packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.mm
packages/react-native-bottom-tabs/ios/RCTTabViewViewManager.mm
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProps.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
packages/react-native-bottom-tabs/src/TabView.tsx
packages/react-native-bottom-tabs/src/TabViewNativeComponent.ts
packages/react-navigation/src/index.tsx
packages/react-navigation/src/types.ts
packages/react-navigation/src/views/NativeBottomTabView.tsx
yarn.lock

This PR implements option to hide the tabBar closing: https://github.com/callstackincubator/react-native-bottom-tabs/discussions/214
Additionally unlocks adding custom tab bars as elements! 
TBD

feat: allow for custom JS tab bars

---

docs/docs/docs/getting-started/how-is-it-different.mdx
docs/docs/docs/guides/usage-with-react-navigation.mdx

docs: add custom tab bars documentation, update how is it different

---

.changeset/cold-rabbits-grin.md
apps/example/src/Screens/Chat.tsx
apps/example/src/Screens/Contacts.tsx
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
packages/react-native-bottom-tabs/src/TabView.tsx

This PR resolves: #276 
Canary release: `react-native-bottom-tabs@0.8.6-canary-20250206123021`
N/A

fix: make pressable items work when switching screens on new arch

---

.changeset/dirty-kids-attack.md
apps/example/src/App.tsx
apps/example/src/Examples/Labeled.tsx
packages/react-native-bottom-tabs/ios/TabViewProps.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
packages/react-native-bottom-tabs/src/TabView.tsx

This PR properly handles labeled false on iOS

fix: properly handle labeled false on iOS

---

.changeset/funny-oranges-applaud.md
packages/react-native-bottom-tabs/android/build.gradle

When using a app theme with a Material 3 parent theme a dynamic `tabBarIcon` based on `focused` stopped working in version 0.8.0. This change fixes this

fix: upgrade material to alpha10 so dynamic tabBarIcon works on Material 3

---

packages/react-native-bottom-tabs/README.md

Remove video url from the `package`'s README.md file because npm don't render it properly
There's another README.md in the root of this directory which still will contain nice looking video :D 
n/a
n/a

fix: remove video url from packages's `README.md`

---

.changeset/purple-beers-laugh.md
packages/react-native-bottom-tabs/ios/TabViewImpl.swift

This PR resolves #293 
Use custom header

fix(ios): prevent header showing on iPad when using a custom one

---

.changeset/friendly-items-invent.md
apps/example/src/App.tsx
apps/example/src/Examples/NativeBottomTabs.tsx
apps/example/src/Examples/NativeBottomTabsFreezeOnBlur.tsx
apps/example/src/Examples/NativeBottomTabsSVGs.tsx
docs/docs/docs/guides/standalone-usage.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
packages/react-native-bottom-tabs/package.json
packages/react-native-bottom-tabs/src/DelayedFreeze.tsx
packages/react-native-bottom-tabs/src/Screen.tsx
packages/react-native-bottom-tabs/src/TabView.tsx
packages/react-native-bottom-tabs/src/types.ts
packages/react-navigation/src/types.ts
packages/react-navigation/src/views/NativeBottomTabView.tsx
yarn.lock

This PR implements freezeOnBlur by using `react-freeze` directly. Should close: #71 
1. Enable freezeOnBlur
2. Check if setTimeout is not called
N/A

feat: implement freezeOnBlur

---

.changeset/young-experts-exercise.md
packages/react-native-bottom-tabs/ios/TabItemEventModifier.swift
packages/react-native-bottom-tabs/ios/TabViewImpl.swift

This PR makes "More Tab" pressable. 
However, the current limitation is that the screens in the more tab must have `lazy: false` otherwise they won't be shown.
Resolves: #278 
https://github.com/user-attachments/assets/8b47d06c-39b5-493b-baf6-4956a5d972b2

feat: make more tab pressable

---

packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt

This PR implements drawable cache which should make tab switching faster + fixes: #298 
https://github.com/user-attachments/assets/43ec7cc5-1b16-4f4b-901a-1f44a381dde2

feat: implement drawable cache

---

.changeset/gorgeous-carpets-cheat.md
packages/react-native-bottom-tabs/src/TabView.tsx

This PR skips screen measurements when using a custom tab bar.

feat: skip screen measurements when using custom tab bar

---

docs/docs/docs/getting-started/quick-start.mdx

Current docs specify static framework linking must be enabled for installation, however it is possible to just use expo-build-properties to specify the 2 pods that require modular_headers support to be installed as extra pods (which was the reason why static framework linking had to be enabled in the first place). 
The extraPods option appears to implement essentially the code in the following podfile without having to enable static linking in Expo 
https://github.com/callstackincubator/react-native-bottom-tabs/blob/1b0ed94579bb234afc047a0bae7f2463cb125de0/example/ios/Podfile
Docs update
Just do a fresh new build

Provide alternative to enabling static framework on Expo using expo-build-properties

---

.changeset/lucky-dots-cheat.md
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt
packages/react-native-bottom-tabs/android/src/oldarch/RCTTabViewManager.kt

`imageLoader.shutdown()` is called `onDetachedFromWindow`. But this lifecycle method is called when opening a modal on top of the current view containing bottom tabs. When then closing the modal the `ImageLoader` has been shutdown and wont load icons anymore. Solved this by checking if `imageLoader` is null in the `getDrawable` method and if so creates it again.
Fixes #309 
1. Download fork at https://github.com/johankasperi/react-native-bottom-tabs/tree/android-modal-tabbaricon-bug
2. Run example app on Android
3. Open "Embedded Stacks" example
4. Open the modal and close it again
5. Change between the tabs and see that the icon changes when they are focused

fix: shutdown ImageLoader onDropViewInstance on android

---

.changeset/metal-rocks-shop.md
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt

This PR uses `.firstOrNull` instead of `.first` which doesn't throw an exception.

fix: don't crash when no elements are found

---

.changeset/chilly-chefs-divide.md
packages/react-native-bottom-tabs/react-native-bottom-tabs.podspec

This PR drops support for React Native < 0.71 (since officially last 3 versions are supported)

chore: drop support for < RN 0.71

---

.changeset/shaky-rules-sing.md
apps/example/src/Screens/Contacts.tsx
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabViewImpl.kt
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/events/OnTabBarMeasuredEvent.kt
packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt
packages/react-native-bottom-tabs/android/src/oldarch/RCTTabViewManager.kt

This PR reports tab bar height on Android. When using the `useTabBarHeight()` hook:

feat: report tab bar height on Android

---

.changeset/giant-years-turn.md
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
packages/react-native-bottom-tabs/src/TabView.tsx

The default maximum number of screens allowed by Android's bottom navigation view is 6. I think the reasoning is to prevent people from over-populating the bottom tab bar. However, there are two situations that I can think of that require more than 6 tabs:
1. You have a custom tab bar and just want to use the native transition animations
2. You are explicitly hiding some tabs from the tab bar, but still want to be able to navigate to other screens and have the nav bar visible.
The goal isn't to make the nav bar look ugly, but provide more flexibility for "hidden" screens or custom tab bars.
Update the example app to have more than 6 screens and see them all appear in the bottom tab bar. Make some screens hidden from the tab bar but still provide a way to navigate to them (maybe add a …

feat: Support more than 6 screens on Android

---

.github/workflows/ci.yml
.swiftlint.yml
packages/react-native-bottom-tabs/ios/Events/OnNativeLayoutEvent.swift
packages/react-native-bottom-tabs/ios/Events/PageSelectedEvent.swift
packages/react-native-bottom-tabs/ios/Events/TabBarMeasuredEvent.swift
packages/react-native-bottom-tabs/ios/Events/TabLongPressedEvent.swift
packages/react-native-bottom-tabs/ios/Extensions.swift
packages/react-native-bottom-tabs/ios/RepresentableView.swift
packages/react-native-bottom-tabs/ios/TabItem.swift
packages/react-native-bottom-tabs/ios/TabItemEventModifier.swift
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProps.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift

fix: setup swift-lint

---

.changeset/ready-paths-train.md
apps/example/ios/Podfile.lock
apps/example/src/Examples/SFSymbols.tsx
docs/docs/docs/guides/standalone-usage.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt
packages/react-native-bottom-tabs/android/src/oldarch/RCTTabViewManager.kt
packages/react-native-bottom-tabs/ios/Fabric/RCTTabViewComponentView.mm
packages/react-native-bottom-tabs/ios/RCTTabViewViewManager.mm
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProps.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
packages/react-native-bottom-tabs/src/TabView.tsx
packages/react-native-bottom-tabs/src/TabViewNativeComponent.ts

https://github.com/user-attachments/assets/18ce87e2-b0af-4546-bb9f-aa656a11dca5

feat: implement iOS 26 minimize behavior

---

.changeset/khaki-maps-lay.md
apps/example/src/Examples/FourTabs.tsx
docs/docs/docs/guides/standalone-usage.md
docs/docs/docs/guides/usage-with-react-navigation.mdx
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabViewImpl.kt
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift
packages/react-native-bottom-tabs/src/TabView.tsx

This PR adjusts the behavior of empty string in the badge prop. It provides a consistent experience across platforms, now to get a "dot" badge you need to pass an empty space `" "`, this is a limitation of iOS prop parsing where std::string is always initialized as an empty string.
Here is a comparison of Android/iOS 18/iOS 26

fix: adjust behavior of empty string in badge prop

---

.changeset/fancy-papayas-battle.md
packages/react-native-bottom-tabs/ios/PlatformAliases.swift
packages/react-native-bottom-tabs/ios/TabBarFontSize.swift
packages/react-native-bottom-tabs/ios/TabViewImpl.swift

This PR adjusts default font sizes per platform according to this article: https://www.learnui.design/blog/ios-font-size-guidelines.html
Also addresses this issue: #375

fix: adjust default font size per platform

---

.changeset/bright-windows-sip.md
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt

When using a custom font with bottom tabs today on Android, another font size is also set by default. With the biggest difference from the standard one being that it scales with the system font scale, which the default one does not. 
**Improvement**: This splits the application of text appearance, so that size and typeface(family and weight) is applied individually. So that when setting one or the other, only that is applied. So one could use a custom font family, without getting the font scaling which is usually not wanted with tab bars.
On Android apply `fontFamily`+`fontWeight` and `fontSize` individually in `tabLabelStyle`, and see they can be used individually.
Before and after examples with bigger system font scale on Android
| Code | Before | After |
|--------|--------|--------| …

Apply typeface and size individually in android text appearance.

---

.changeset/dull-walls-share.md
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift

feat(iOS): make tabview background transparent

---

.changeset/shy-masks-accept.md
packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt

This PR shows a small badge when passing an empty string to show just a dot.
Closes #422

fix: show small badge on Android when passing empty space

---

.changeset/busy-seals-relax.md
packages/react-native-bottom-tabs/ios/TabBarFontSize.swift
packages/react-native-bottom-tabs/ios/TabViewImpl.swift
packages/react-native-bottom-tabs/ios/TabViewProps.swift
packages/react-native-bottom-tabs/ios/TabViewProvider.swift

This PR fixes compilation issues for macOS.

fix: make sure everything works correctly on macOS

---

.changeset/olive-rockets-take.md
docs/docs/docs/guides/android-native-styling.mdx
packages/react-native-bottom-tabs/android/build.gradle
packages/react-native-bottom-tabs/src/expo.ts

This PR adds support for material 3 expressive in bottom tabs. 
The bottom navigation looks pretty much exactly the same 😆 But its now shorter
Changes from the material design docs:
Changes from M3:
Height: From 80dp to 64dp
Color: New expressive colors!
Top item padding: From 12dp to 6dp
Bottom item padding: From 16dp to 6dp
Label text is no longer bolded when selected
Active indicator: From 64dp to 56dp
New horizontal item configuration on medium and larger window sizes (greater than or equal to 600dp):
Icon moves from top to start of item
Instead of being a set width based on the item count, item width is based on content with a max width
Item gravity: From top center to center

feat: support material3 expressive
