ios/RCTTabViewViewManager.mm
The include is different when frameworks are used. 
This PR adjusts the imports
=> feat: add support for use_frameworks

README.md
Trying to save a link on the newsletter 👼
=> docs: update readme with Expo Router demo/instructions repo

ios/TabViewImpl.swift
=> fix: horizontal safe area layout

README.md, android/src/main/java/com/rcttabview/RCTTabViewViewManager.kt, example/ios/Podfile.lock, example/src/App.tsx, example/src/Examples/FourTabs.tsx, ios/RCTTabViewViewManager.mm, ios/TabViewImpl.swift, ios/TabViewProvider.swift, src/TabView.tsx
=> feat: add `disablePageAnimations` prop

docs/docs/styles/index.css, docs/rspress.config.ts
added a theme for `rspress` from Re.Pack
=> docs: use doc style from repack

ios/TabViewProvider.swift
=> fix: properly set icon aspect ratio

src/react-navigation/views/NativeBottomTabView.tsx
This PR makes the library compatible with RN Navigation 7
=> fix: make it work with RN Navigation 7

package.json
react-native.config.js wasn't included
=> fix: codegen for Android

example/src/Examples/SFSymbols.tsx, ios/TabViewImpl.swift
This PR fixes: #95 
https://github.com/user-attachments/assets/4f698508-8573-43d4-80c6-04023d1ef014
=> feat: allow for not filled sf symbols

docs/docs/docs/getting-started/introduction.mdx
=> docs: mark tvOS as supported platform

docs/docs/docs/guides/usage-with-react-navigation.mdx
add missing Android-Only badge
=> docs: add missing Android-Only badge

example/src/App.tsx, ios/TabViewImpl.swift
This PR resolves #16 
https://github.com/user-attachments/assets/4e99e67f-2b8b-407d-8dc3-a4ea2d431ffe
The native "More" Tab is now properly handled
=> fix: make more tab work

docs/docs/docs/guides/usage-with-react-navigation.mdx
This PR adds missing prop to docs
=> docs: add missing prop

ios/TabViewImpl.swift
=> fix: white screen on compiler <6.0

docs/docs/docs/guides/usage-with-expo-router.mdx, docs/docs/docs/guides/usage-with-one.mdx, docs/docs/docs/guides/usage-with-react-navigation.mdx, docs/docs/docs/guides/usage-with-vector-icons.md, package.json, turbo.json
This PR documents the new React Navigation package for 0.6.0 release. 
N/A
N/A
=> docs: document new package

.github/workflows/release.yml
This PR adds changesets CI
CI Green
=> feat: add changesets ci

.changeset/config.json, .github/workflows/release.yml
=> feat: automate changesets

.changeset/silly-coins-shave.md, .github/workflows/release.yml
This PR sets up provenance for releasing packages.
=> chore: setup provenance

packages/react-native-bottom-tabs/package.json
This PR adds the newly required field to map component providers to their names.
=> feat: add component provider field for codegen

.changeset/brown-apricots-guess.md, packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/ImageSource.kt
This PR should resolve build issues faced here: #237
=> fix(android): build issues ResourceDrawableIdHelper.instance

.github/workflows/release-canary.yml
This PR adds release canary job
=> chore: add release canary job

.changeset/ninety-garlics-bow.md, packages/react-native-bottom-tabs/android/src/main/java/com/rcttabview/RCTTabView.kt
This PR fixes appearance-switching issues on Android: #310 
We now only bail out of automatic appearance switching when user changes the background color.
Change appearance, see if everything works 
N/a
=> fix: appearance issues with dark mode switches on Android

docs/docs/docs/getting-started/quick-start.mdx
- doc improvement by adding `npx expo install expo-build-properties` step
=> docs: update quick-start.mdx

.changeset/tricky-waves-tap.md, packages/react-native-bottom-tabs/android/src/newarch/RCTTabViewManager.kt
This PR fully removes ignoresSafeAreaTop prop
=> fix(android): remove unnecessary override causing issues

.changeset/wet-mammals-kiss.md, packages/react-native-bottom-tabs/ios/Extensions.swift
https://github.com/user-attachments/assets/effed7ec-191a-4656-a372-c55a7b062218
=> fix: introspect on all future operating systems, make iOS 26 properly switch tabs

.changeset/nasty-taxes-lay.md, packages/react-native-bottom-tabs/package.json
This PR includes common folder in files shipped to npm
=> fix: include common in files shipped to npm

.changeset/dirty-mails-search.md, packages/react-native-bottom-tabs/babel.config.js, packages/react-native-bottom-tabs/package.json
This PR fixes package.json and bob config so things can be imported again
=> fix: release and bob config
